# [Not recommended] Use this configuration only when utilizing the disjointed
# os_sensor and os_cloud configuration
# For the future and for better results consider migrating to combined node/component os_driver
# and utilize the driver_params.yaml along with it. 
ouster/os_sensor:
  ros__parameters:
    sensor_hostname: 'os-122406002537.local'
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '2048x10'
    timestamp_mode: 'TIME_FROM_PTP_1588'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 0
    imu_port: 0
    use_system_default_qos: false
ouster/os_cloud:
  ros__parameters:
    sensor_frame: os_sensor
    lidar_frame: os_lidar
    imu_frame: os_imu
    point_cloud_frame: os_lidar
    timestamp_mode: 'TIME_FROM_PTP_1588'  # this value needs to match os_sensor/timestamp_mode
    ptp_utc_tai_offset: 0.0 # UTC/TAI offset in seconds to apply when using TIME_FROM_PTP_1588
    proc_mask: IMU|PCL|SCAN # pick IMU, PCL, SCAN or any combination of the three options
    use_system_default_qos: false # needs to match the value defined for os_sensor node
    scan_ring: 0  # Use this parameter in conjunction with the SCAN flag and choose a
                  # value the range [0, sensor_beams_count)
    point_type: original # choose from: {original, native, xyz, xyzi, xyzir}
ouster/os_image:
    use_system_default_qos: false # needs to match the value defined for os_sensor node